config/routes.rb
Rails.application.routes.draw do
  get '/users/new', to: 'users#new', as: 'new_user'
  root 'static_pages#home'
  get '/users', to:'users#index', as: 'users'
  post '/users', to:'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  get '/attractions', to: 'attractions#index', as: 'attractions'
  get '/signin', to: 'session#new', as: 'signin'
  post '/session', to: 'session#create', as: 'session'
  delete '/session/', to: 'session#destroy'
  get '/attractions/new', to: 'attractions#new', as: 'new_attraction'
  get '/attractions/:id', to: 'attractions#show', as: 'attraction'
  get '/attractions/:id/edit', to: 'attractions#edit', as: 'edit_attraction'
  patch '/attractions/:id', to: 'attractions#update'
  post '/attractions', to: 'attractions#create'
  post '/rides', to:"rides#create", as: 'rides'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
  has_many :rides
  has_many :users, :through => :rides
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :user
  belongs_to :attraction

  def take_ride
    user_has_enough_tickets, user_is_tall_enough = check_if_user_meets_the_requirements
    if user_has_enough_tickets && user_is_tall_enough
      start_ride
    elsif user_is_tall_enough && !user_has_enough_tickets
      "Sorry. " + not_enough_tickets
    elsif user_has_enough_tickets && !user_is_tall_enough
      "Sorry. " + not_tall_enough
    else
      "Sorry. " + not_enough_tickets + " " + not_tall_enough
    end
  end

  def check_if_user_meets_the_requirements
    user_has_enough_tickets, user_is_tall_enough = false
    if self.user.tickets >= self.attraction.tickets
      user_has_enough_tickets = true
    end
    if self.user.height >= self.attraction.min_height
      user_is_tall_enough = true
    end
    return [user_has_enough_tickets, user_is_tall_enough]
  end

  def start_ride
    new_happiness = self.user.happiness + self.attraction.happiness_rating
    new_nausea = self.user.nausea + self.attraction.nausea_rating
    new_tickes_count =  self.user.tickets - self.attraction.tickets
    self.user.update(
      :happiness => new_happiness,
      :nausea => new_nausea,
      :tickets => new_tickes_count
    )
    "Thanks for riding the #{self.attraction.name}!"
  end

  def not_enough_tickets
    "You do not have enough tickets to ride the #{self.attraction.name}."
  end

  def not_tall_enough
    "You are not tall enough to ride the #{self.attraction.name}."
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :rides
  has_many :attractions, through: :rides

  def mood
    # has a method 'mood' that returns 'sad' when the user is more nauseous than happy
    # has a method 'mood' that returns 'happy' when the user is more happy than nauseous
    unless admin
      happiness > nausea ? 'happy' : 'sad'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :verify_user_is_authenticated
  helper_method :current_user

  private
  def verify_user_is_authenticated
    redirect_to '/' unless user_is_authenticated
  end

  def user_is_authenticated
    !!current_user
  end

  def current_user
    User.find_by(id:session[:user_id])
  end
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  def index
    @attractions = Attraction.all
  end

  def show
    @attraction = Attraction.find_by(id: params[:id])
    @ride = @attraction.rides.build(user_id:current_user.id)
  end

  def new
    @attraction = Attraction.new
  end

  def create
    attraction = Attraction.create(attraction_params)
    redirect_to attraction_path(attraction)
  end

  def edit
    @attraction = Attraction.find_by(id: params[:id])
    @ride = @attraction.rides.build(user_id:current_user.id)
  end

  def update
    attraction = Attraction.find_by(id: params[:id])
    attraction.update(attraction_params)
    redirect_to attraction_path(attraction)
  end

  private
  def attraction_params
    params.require(:attraction).permit(
        :name,
        :min_height,
        :tickets,
        :happiness_rating,
        :nausea_rating
      )
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def create
    ride = Ride.create(ride_params)
    message = ride.take_ride
    redirect_to user_path(ride.user), flash: { message:message }
  end

  private
  def ride_params
    params.require(:ride).permit(
      :user_id,
      :attraction_id
      )
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :verify_user_is_authenticated, only: [:new,:create]
  def new
    @user = User.new
  end

  def create
    if @user = User.find_by(name:params[:user][:name])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def destroy
    session.delete("user_id")
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :verify_user_is_authenticated, only: [:home]
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_user_is_authenticated, only: [:new,:create]
  def new
    @user = User.new
  end

  def create
    if (user = User.create user_params)
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(id:params[:id])
  end

  private
  def user_params
    params.require(:user).permit(
      :name,
      :height,
      :height,
      :nausea,
      :tickets,
      :admin,
      :admin,
      :password,
      :happiness
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attractions/_form.html.erb
<%= form_for(@attraction) do |f| %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :min_height, "Height Requirement (in inches)" %><br>
    <%= f.number_field :min_height, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :happiness_rating, "How fun is it? (1-5 scale)" %><br>
    <%= f.number_field :happiness_rating, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :nausea_rating, "How nausea-inducing is it? (1-5 scale)" %><br>
    <%= f.number_field :nausea_rating, class: "form-control" %></div>

  <div class="form-group">
    <%= f.label :tickets, "How many tickets does it cost?" %><br>
    <%= f.number_field :tickets, class: "form-control" %></div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing attraction</h1>

<%= render 'form' %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
<h1>Listing attractions</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr> 
      <td><strong>Name</strong></td>
      <td><strong>Tickets</strong></td>
      <td><strong>Details</strong></td>
    </tr>
    <% @attractions.each do |attraction| %>
      <tr>

        <td><%= attraction.name %></td>
        <td><%= attraction.tickets %></td>
        <% if current_user.admin %>
          <td><%= link_to "Show #{attraction.name}", attraction_path(attraction) %></td>
        <% else %>
          <td><%= link_to "Go on #{attraction.name}", attraction_path(attraction) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% if @user %>
  <p>
    <%= link_to "Back to profile", user_path(@user), {:class => "btn btn-primary"} %>
  </p>
<% else %>
  <p><%= link_to 'New Attraction', new_attraction_path %></p>
<% end %>

app/views/attractions/new.html.erb
<h1>New attraction</h1>

<%= render 'form' %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="center">

  <div class="info">
    <p><strong>Name:</strong> <%= @attraction.name %></p>
    <p><strong>Total Number of Users:</strong> <%= @attraction.users.count %></p>
    <p><strong>Ticket Requirement:</strong> <%= @attraction.tickets %></p>
    <p><strong>Height Requirement:</strong> <%= @attraction.min_height %> inches</p>
    <p><strong>Nausea Rating:</strong> <%= @attraction.nausea_rating %></p>
    <p><strong>Happiness Rating:</strong> <%= @attraction.happiness_rating %></p>
    <% if current_user.admin %>
      <%= link_to 'Edit Attraction', [:edit, @attraction] %></p>
    <% else %>
      <%= form_for @ride do |f| %>
        <%= f.hidden_field :user_id %><br />
        <%= f.hidden_field :attraction_id %><br />
        <%= f.submit "Go on this ride", class:"btn btn-light" %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAmusementPark</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        
        <% if !current_user %>
          <a class="navbar-brand" href="<%= new_user_path %>"/>Sign Up</a>
          <%= link_to "Log in", signin_path, class:"navbar-brand" %>
        <% end %>
        <% if current_user %>
          <%= link_to "#{current_user.name}'s profile", user_path(current_user), class:"navbar-brand"%>
          <%= link_to "Log Out", session_path, class:"navbar-brand",method:'delete' %>
        <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/session/new.html.erb
<%= form_tag('/session', method: :post) do %>

  <div class="form-group">
    <%= label_tag(:name, "Your name:") %>

    <%= collection_select(:user, :name, User.all, :name, :name, prompt: "Please select your username from this dropdown") %>
  </div>

  <div class="form-group">
    <%= label_tag(:password, "Your password:") %>
    <%= password_field_tag(:password, nil, class: "form-control") %>
  </div>

  <div class="actions">
    <%= submit_tag("Sign In") %>
  </div>

<% end %>

app/views/static_pages/home.html.erb
<div>
  <div style='width: 600px;margin:auto'>
    <img  style='width: 600px' src="http://www.washingtonpost.com/wp-srv/special/health/why-roller-coasters-make-us-scream/images/rollercoasterBackground.jpg">
  </div>
  <h1 align="center">Welcome to the //Amusement Park!</h1>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :height, "Height (in inches)" %>
    <br>
    <%= f.number_field :height, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :happiness, "How happy are you? (1-5 scale)" %>
    <br>
    <%= f.number_field :happiness, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :nausea, "How nauseous are you? (1-5 scale)" %>
    <br>
    <%= f.number_field :nausea, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tickets, "How many dollars are in your pocket?" %>
    <br>
    <%= f.number_field :tickets, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :admin, "Check box if you are a theme park owner" %>
    <%= f.check_box :admin, class: "form-check-input" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <br>
    <%= f.password_field :password, class: "form-control" %>

  <div class="actions">
    <br/>
    <%= f.submit class: "btn btn-primary" %>
  </div>
  
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>



<% if flash[:message] %>
  <div class="center alert">
    <p><%= flash[:message] %></p>
  </div>
<% end %>

<div class="center">

  <div class="info">
    <% if @user.admin %>
      <p><strong>ADMIN</strong></p>
    <% end %>
    <p><strong>Name:</strong> <%= @user.name %></p>
    <p><strong>Tickets:</strong> <%= @user.tickets %></p>
    <p><strong>Mood:</strong>  <%= @user.mood %></p>
    <p><strong>Height:</strong> <%= @user.height %> inches</p>
    <p><%= link_to 'See attractions', attractions_path %></p>
  </div>
</div>